ePark.WebUI/Areas/Admin/ViewModels/ContractViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using ePark.Data;
using ePark.Managers;


namespace ePark.WebUI.Areas.Admin.Models
{
    public class ContractViewModel
    {
        [DisplayName("Name")]
        public string FirstLastName { get; set; }

        public Group Grp { get; set; }

        public Inquiry Inq { get; set; }

        public AspNetUser aspUser { get; set; }

        public vwInquiry InqView { get; set; }

        // ASPNet User

        public int? ASPNetUserId { get; set; }

        [StringLength(256)]
        [DisplayName("Email")]
        public string Email { get; set; }

        [DisplayName("Phone")]
        public string PhoneNumber { get; set; }
        
        [StringLength(256)]
        [DisplayName("User Name")]
        public string UserName { get; set; }
        [DisplayName("Address")]
        public string Address1 { get; set; }
        
        //Inquiry

        public int InquiryID { get; set; }

        public int? InquiryTypeID { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        [DisplayName("Inquiry Created")]
        public DateTime? InquiryCreateDate { get; set; }

        public string Notes { get; set; }
        [DisplayName("Inquiry Approved")]
        public bool IsApproved { get; set; }

        [DisplayName("Approved Date")]
        public DateTime? ApprovedDate { get; set; }

        // Contract
        public int ContractID { get; set; }

        public int? ContractStatusID { get; set; }

        public int? EntityID { get; set; }

        public DateTime? ContractCreateDate { get; set; }

        public bool? ContractIsActive { get; set; }

        // Group
        public int GroupID { get; set; }

        public int? GroupCategoryID { get; set; }

        [DisplayName(" Group")]
        public string GroupDesc { get; set; }

        public bool? GroupIsActive { get; set; }

        // GroupRate
        public int GroupRatesID { get; set; }

        public DateTime? GroupRateBegin { get; set; }

        public DateTime? GroupRateEnd { get; set; }
        [DisplayName("Amount")]
        public decimal? Amount { get; set; }

        public bool? GroupRateIsActive { get; set; }

        [DisplayName("Group")]
        public int SelectedGroupId { get; set; }
        public IEnumerable<SelectListItem> ContractGroups { get; set; }
    }
}

ePark.WebUI/Areas/Admin/Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ePark.Data;
using ePark.WebUI.Areas.Admin.Models;
using BnB.Common.Mail;
using ePark.Managers;
using ePark.WebUI.Controllers;
using ePark.WebUI.Helpers;
using ePark.WebUI.Models.Enums;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace ePark.WebUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ContractsController : BaseController
    {
        private EparkContext db = new EparkContext();

        // GET: Admin/Contracts
        public ActionResult Index()
        {
            var contracts = db.Contracts.Include(c => c.AspNetUser).Include(c => c.ContractStatu).Include(c => c.Group);
            return View(contracts.ToList());
        }

        // GET: Admin/Contracts
        public ActionResult InquiryList()
        {
            var contracts = db.Contracts.Include(c => c.AspNetUser).Include(c => c.ContractStatu).Include(c => c.Group);
            return View(contracts.ToList());
        }

        // GET: Admin/Contracts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contract contract = db.Contracts.Find(id);
            if (contract == null)
            {
                return HttpNotFound();
            }
            return View(contract);
        }

        // GET: Admin/Contracts/Create
        public ActionResult Create()
        {
            ViewBag.AspNetUserID = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.ContractStatusID = new SelectList(db.ContractStatus, "ContractStatusID", "ContractStatusDesc");
            ViewBag.GroupID = new SelectList(db.Groups, "GroupID", "GroupDesc");
            return View();
        }

        // POST: Admin/Contracts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ContractID,ContractStatusID,AspNetUserID,EntityID,GroupID,CreateDate,IsActive")] Contract contract)
        {
            if (ModelState.IsValid)
            {
                db.Contracts.Add(contract);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AspNetUserID = new SelectList(db.AspNetUsers, "Id", "Email", contract.AspNetUserID);
            ViewBag.ContractStatusID = new SelectList(db.ContractStatus, "ContractStatusID", "ContractStatusDesc", contract.ContractStatusID);
            ViewBag.GroupID = new SelectList(db.Groups, "GroupID", "GroupDesc", contract.GroupID);
            return View(contract);
        }

        // GET: Admin/Contracts/Edit/5
        public ActionResult Edit(int id)
        {

            var contractModel = PopulateInquiry(id);

            return View(contractModel);
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Contract contract = db.Contracts.Find(id);
            //if (contract == null)
            //{
            //    return HttpNotFound();
            //}
            //ViewBag.AspNetUserID = new SelectList(db.AspNetUsers, "Id", "Email", contract.AspNetUserID);
            //ViewBag.ContractStatusID = new SelectList(db.ContractStatus, "ContractStatusID", "ContractStatusDesc", contract.ContractStatusID);
            //ViewBag.GroupID = new SelectList(db.Groups, "GroupID", "GroupDesc", contract.GroupID);
            //return View(contract);
        }

        public ContractViewModel PopulateInquiry(int id)
        {
            var contractModel = new ContractViewModel();
            var groupManager = new GroupManager();
            var inquiryViewMgr = new InquiryViewManager();
            var aspuser = new AspNetUsersManager();

            contractModel.InqView = inquiryViewMgr.GetByInqId(id);

            contractModel.UserName = contractModel.InqView.UserName;
            contractModel.InquiryID = contractModel.InqView.InquiryID;
            contractModel.ContractGroups = GetGroups();
            contractModel.Grp = groupManager.GetById(contractModel.InqView.GroupID.Value);
            contractModel.SelectedGroupId = contractModel.InqView.GroupID.Value;
            contractModel.IsApproved = (bool)contractModel.InqView.IsApproved;
            contractModel.InquiryCreateDate = contractModel.InqView.CreateDate;
            contractModel.Address1 = contractModel.InqView.Address1;
            contractModel.FirstLastName = contractModel.InqView.FirstName + " " + contractModel.InqView.LastName;
            contractModel.Email = contractModel.InqView.Email;
            contractModel.ASPNetUserId = contractModel.InqView.Id;
            contractModel.Amount = contractModel.InqView.Amount;
            return contractModel;
        }

        private IEnumerable<SelectListItem> GetGroups()
        {
            var grouprates = new GroupCategoryRateManager();

            var grplist = grouprates.GetList().Where(gr => gr.GroupRateIsActive == true && gr.GroupRateBegin <= System.DateTime.Now && System.DateTime.Now <= gr.GroupRateEnd)
                .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.GroupID.ToString(),
                                    Text = x.GroupDesc + " $" + string.Format("{0:#.00}", x.Amount)
                                });

            return new SelectList(grplist, "Value", "Text");

        }
        // POST: Admin/Contracts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ContractID,ContractStatusID,AspNetUserID,EntityID,GroupID,CreateDate,IsActive")] Contract contract)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(contract).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.AspNetUserID = new SelectList(db.AspNetUsers, "Id", "Email", contract.AspNetUserID);
        //    ViewBag.ContractStatusID = new SelectList(db.ContractStatus, "ContractStatusID", "ContractStatusDesc", contract.ContractStatusID);
        //    ViewBag.GroupID = new SelectList(db.Groups, "GroupID", "GroupDesc", contract.GroupID);
        //    return View(contract);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContractViewModel model)
        {
            var aspnetUserProfilesManager = new AspNetUserProfilesManager();
            var aspnetUsersManager = new AspNetUsersManager();
            var contractManager = new ContractManager();

            var aspnetUser = aspnetUsersManager.GetById((int)model.ASPNetUserId);
            var aspnetUserProfile = aspnetUserProfilesManager.GetById((int)model.ASPNetUserId);

            var applicationUserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            string emailConfirmationToken = applicationUserManager.GenerateEmailConfirmationToken(aspnetUserProfile.Id);

            int groupSelected = model.SelectedGroupId;
            int inqID = model.InquiryID;

            model.GroupID = model.SelectedGroupId;

            try
            {
                UpdateInquiry(model);

                if (model.IsApproved)
                {
                    MailManager.EmailActivationInstructions(model.ASPNetUserId.Value, emailConfirmationToken);
                    model.ContractID = contractManager.GetByAspNetUserId(aspnetUser.Id).ContractID;
                    CreateContractTrans(model);
                }
            }
            catch (Exception ex)
            {
                string strMsg = ex.Message.ToString();
                ModelState.AddModelError("", "We encountered an error saving your record.  Please try again.");
                return View(model);
            }

            CreateAlert(AlertType.Success, String.Format("You successfully updated Inquiry #{0}.", model.InquiryID));
            return RedirectToAction("Index", "Dashboard", new { area = "Admin" });
        }

        private void UpdateInquiry(ContractViewModel contractViewModel)
        {
            var inquiryManager = new InquiryManager();
            var inquiry = inquiryManager.GetById(contractViewModel.InquiryID);

            inquiry.GroupID = contractViewModel.SelectedGroupId;
            inquiry.IsApproved = contractViewModel.IsApproved;
            inquiry.ApprovedDate = System.DateTime.Now;

            int result = inquiryManager.Update(inquiry);
        }

        private void CreateContractTrans(ContractViewModel contractViewModel)
        {
            var contractTransactionManager = new ContractTransactionManager();
            var groupCategoryRateManager = new GroupCategoryRateManager();
            var systemParametersManager = new SystemParametersManager();
            var systemParameter = new SystemParameter();

            var contractTransaction = CreateContractTransaction(contractViewModel);
            var vwGroupCategoryRate = groupCategoryRateManager.GetByGroupId(contractViewModel.GroupID);

            try
            {
                contractTransaction.Amount = vwGroupCategoryRate.Amount;
                contractTransaction.GroupID = contractViewModel.GroupID;

ePark.WebUI/Areas/Admin/Views/Contracts/Create.cshtml
@model ePark.Data.Contract

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Contract</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ContractStatusID, "ContractStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ContractStatusID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ContractStatusID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AspNetUserID, "AspNetUserID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AspNetUserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AspNetUserID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.EntityID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EntityID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EntityID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.GroupID, "GroupID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("GroupID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ePark.WebUI/Areas/Admin/Views/Contracts/Delete.cshtml
@model ePark.Data.Contract

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Contract</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AspNetUser.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ContractStatu.ContractStatusDesc)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ContractStatu.ContractStatusDesc)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Group.GroupDesc)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Group.GroupDesc)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EntityID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EntityID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreateDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreateDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

ePark.WebUI/Areas/Admin/Views/Contracts/Details.cshtml
@model ePark.Data.Contract

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Contract</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AspNetUser.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ContractStatu.ContractStatusDesc)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ContractStatu.ContractStatusDesc)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Group.GroupDesc)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Group.GroupDesc)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.EntityID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EntityID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreateDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreateDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ContractID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

ePark.WebUI/Areas/Admin/Views/Contracts/Edit.cshtml
@using ePark.WebUI.Helpers
@model ePark.WebUI.Areas.Admin.Models.ContractViewModel
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
        <h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-user"></i> Inquiry Maintenance <span>&gt; Manage Inquiry</span></h1>
    </div>
</div>

<section id="widget-grid" class="">

    @AlertHelper.GetAvailableAlerts(this.ViewContext)

    <div class="row">

        <article class="col-sm-12 sortable-grid ui-sortable">

            <div class="bActivewidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" role="widget">

                <header role="heading">
                    <div class="bActivewidget-ctrls" role="menu">  <a href="@Url.Action("Index", "Dashboard", new {area = "Admin"})" class="button-icon" rel="tooltip" title="" data-placement="bottom" data-original-title="Cancel"><i class="fa fa-times"></i></a></div>
                    <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                    <h2>Inquiry Details</h2>

                    <span class="bActivewidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
                </header>

                <div role="content">

                    <div class="widget-body">
                        @using (Html.BeginForm("Edit", "Contracts", FormMethod.Post, new { type = "form", @class = "form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()

                            <fieldset>
                                <legend>User Information</legend>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.InqView.UserName, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.HiddenFor(model => model.InquiryID)
                                        @Html.HiddenFor(model => model.Email)
                                        @Html.HiddenFor(model => model.ASPNetUserId)
                                        @Html.HiddenFor(model => model.Amount)
                                        <label class="control-label"><strong>@Html.DisplayTextFor(model => model.InqView.UserName)</strong></label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.FirstLastName, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.FirstLastName, new { type = "text", @class = "form-control", tabindex = 1, required = "required" })
                                        @Html.ValidationMessageFor(model => model.InqView.Notes, "", new { @class = "text-danger small" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.Address1, new { type = "text", @class = "form-control",  tabindex = 1 })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.InqView.PhonePrimary, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.HiddenFor(model => model.InqView.PhonePrimary)
                                        @Html.TextBoxFor(model => model.InqView.PhonePrimary, new { type = "text", @class = "form-control", placeholder = "(  ) ___-____", tabindex = 1 })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.InquiryCreateDate, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.HiddenFor(model => model.InquiryCreateDate)
                                        @Html.TextBoxFor(model => model.InquiryCreateDate, new { type = "text", @class = "form-control", tabindex = 1 })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.InqView.Notes, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.InqView.Notes, new { type = "text", @class = "form-control", placeholder = "Enter Notes...", tabindex = 1 })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.SelectedGroupId, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10 has-feedback">
                                        @Html.DropDownListFor(model => model.SelectedGroupId, Model.ContractGroups, htmlAttributes: new { @class = "form-control input-sm" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.IsApproved, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            <label>
                                                @Html.CheckBoxFor(model => model.IsApproved, new { type = "checkbox", @class = "checkbox style-0" })<span></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>

                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12">
                                        <button class="btn btn-primary" name="SubmitEdit" type="submit">
                                            <i class="fa fa-save"></i>
                                            Save
                                        </button>&nbsp;&nbsp;
                                       <a href="@Url.Action("Index", "Dashboard", new {area = "Admin"})" class="btn btn-default">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </article>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ePark.WebUI/Areas/Admin/Views/Contracts/Index.cshtml
@model IEnumerable<ePark.Data.Contract>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContractStatu.ContractStatusDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Group.GroupDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EntityID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContractStatu.ContractStatusDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group.GroupDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EntityID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ContractID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ContractID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ContractID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>