ePark.WebUI/Areas/Admin/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ePark.Data;
using ePark.WebUI.Areas.Admin.Models;
using ePark.Managers;
using ePark.WebUI.Controllers;

namespace ePark.WebUI.Areas.Admin.Controllers
{
    public class UserManagementController : BaseController
    {
        [Authorize(Roles = "Admin")]
        // GET: Admin/UserManagement
        public ActionResult Index()
        {
            var userManagmentModel = new UserManagementModel();
            var vwAspNetUsers = new AspNetUserProfileRolesViewManager();

            userManagmentModel.Users = vwAspNetUsers.GetList();
            
            return View(userManagmentModel);
        }

        public JsonResult ProvideUsers()
        {
            return Json(GetUsers(), JsonRequestBehavior.AllowGet);
        }

        public Array GetUsers()
        {
            var viewAspNetUserProfileRolesManager = new AspNetUserProfileRolesViewManager();

            Array rows = viewAspNetUserProfileRolesManager.GetList().Select(x => new
            {
                x.AspNetUsersId,
                x.UserName,
                x.FirstName,
                x.LastName,
                x.Email,
                x.Address1,
                x.City,
                x.State,
                x.PhonePrimary,
                x.MccEmployee
            }).ToArray();

            return rows;
        }
        
        public ActionResult UserMaint(int userid)
        {
            var model = new UserManagementModel();
            var vwaspnetuser = new AspNetUserProfileRolesViewManager();
            model.Role = new AspNetRole();

            model.User = vwaspnetuser.GetByUserId(userid);

            //model.UserRole = new AspNetUserRole { UserId = (int)model.User.AspNetUsersId };

            //if (model.User.AspNetRolesId != null) model.UserRole.RoleId = (int) model.User.AspNetRolesId;

            if (model.User.Name != null) model.Role.Name = model.User.Name;

            return View(model);
        }

        [HttpPost]
        public ActionResult UserMaint(UserManagementModel model)
        {
            return RedirectToAction("Index");
        }

        private void UpdateUser(int userid)
        {


        }

    }
}

ePark.WebUI/Areas/Admin/Views/UserManagement/Index.cshtml
@{
    ViewBag.Title = "Index";
}
        <div class="row">

            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                <table id="jqgrid"></table>
                <div id="pjqgrid"></div>

                <br>

            </article>

        </div>
@section Scripts {
    @Scripts.Render("~/Areas/Shared/Content/js/plugin/jqgrid/jquery.jqGrid.min.js")
    @Scripts.Render("~/Areas/Shared/Content/js/plugin/jqgrid/grid.locale-en.min.js")

@Scripts.Render("~/Scripts/jqgridsrc/grid.inlinedit.js")

    <script type="text/javascript">
        $(document).ready(function () {
            var grid = $('#jqgrid');
            grid.jqGrid({
                //data: jqgridData,
                datatype: "json",
                url: "UserManagement/ProvideUsers",
                height: 'auto',
                colNames: ['AspNetUsersId', 'User', 'FirstName', 'LastName', 'Address', 'City', 'State', 'Phone', 'Contract'],
                colModel: [
                    {
                        name: 'AspNetUsersId',
                        index: 'AspNetUsersId',
                        hidden: true
                    },
                        {
                        name: 'UserName',
                        index: 'UserName',
                        sortable: false,
                        editable: false//,
                        //formatter: formateadorLink
                    },  {
                        name: 'FirstName',
                        index: 'FirstName',
                        editable: false
                    }, {
                        name: 'LastName',
                        index: 'LastName',
                        editable: false

                    }, {
                        name: 'Address1',
                        index: 'Address1',
                        editable: false
                    }, {
                        name: 'City',
                        index: 'City',
                        editable: true
                    }, {
                        name: 'State',
                        index: 'State',
                        editable: false
                    },
                    {
                        name: 'PhonePrimary',
                        index: 'PhonePrimary',
                        editable: false
                    },
                    
                    {
                        name: 'Contract',
                        fixed: true,
                        formatter: formatTmplteLink
                    }

                ],
                rowNum: 15,
                
                pager: '#pjqgrid',
                loadonce: true,
                altrows: true,
                sortable: true,
                gridview: true,
                emptyRecords: "No records to display",
                caption: "Log",
                sortname: 'id',
                toolbarfilter: true,
                viewrecords: true,
                sortorder: "asc",
                gridComplete: function () {
                    var ids = jQuery("#jqgrid").jqGrid('getDataIDs');
                    for (var i = 0; i < ids.length; i++) {
                        var cl = ids[i];
                        be = "<button class='btn btn-xs btn-default' data-original-title='Edit Row' onclick=\"jQuery('#jqgrid').editRow('" + cl + "');\"><i class='fa fa-pencil'></i></button>";
                        se = "<button class='btn btn-xs btn-default' data-original-title='Save Row' onclick=\"jQuery('#jqgrid').saveRow('" + cl + "');\"><i class='fa fa-save'></i></button>";
                        ca = "<button class='btn btn-xs btn-default' data-original-title='Cancel' onclick=\"jQuery('#jqgrid').restoreRow('" + cl + "');\"><i class='fa fa-times'></i></button>";
                        //ce = "<button class='btn btn-xs btn-default' onclick=\"jQuery('#jqgrid').restoreRow('"+cl+"');\"><i class='fa fa-times'></i></button>";
                        //jQuery("#jqgrid").jqGrid('setRowData',ids[i],{act:be+se+ce});
                        //jQuery("#jqgrid").jqGrid('setRowData', ids[i], {
                        //    act: be + se + ca
                        //});
                    }
                },
                editurl: "dummy.html",

                caption: "ePark Parking Users",
               // multiselect: true,
                autowidth: true,
                onSelectRow: function (AspNetUsersId) {
                    // just get the ID:
                    // alert(id);
                   // alert(AspNetUsersId);
                    // get the ID and other column data
                     var selectedRow = jQuery("#jqgrid").jqGrid("getGridParam", "selrow");
                     var row = jQuery("#jqgrid").jqGrid("getRowData", selectedRow);
                     //alert("You selected: " + row.Id + " With HttpResponse: " + row.AspNetUsersId);

                    //NAVIGATE ON ROW CLICK
                     window.location = "/Admin/UserManagement/UserMaint/?userid=" + row.AspNetUsersId;
                }

            });
            jQuery("#jqgrid").jqGrid('navGrid', "#pjqgrid", {
                edit: false,
                add: false,
                del: true
            });
            jQuery("#jqgrid").jqGrid('inlineNav', "#pjqgrid");
            /* Add tooltips */
            $('.navtable .ui-pg-button').tooltip({
                container: 'body'
            });

            jQuery("#m1").click(function () {
                var s;
                s = jQuery("#jqgrid").jqGrid('getGridParam', 'selarrrow');
                alert(s);
            });
            jQuery("#m1s").click(function () {
                jQuery("#jqgrid").jqGrid('setSelection', "13");
            });

            // remove classes
            $(".ui-jqgrid").removeClass("ui-widget ui-widget-content");
            $(".ui-jqgrid-view").children().removeClass("ui-widget-header ui-state-default");
            $(".ui-jqgrid-labels, .ui-search-toolbar").children().removeClass("ui-state-default ui-th-column ui-th-ltr");
            $(".ui-jqgrid-pager").removeClass("ui-state-default");
            $(".ui-jqgrid").removeClass("ui-widget-content");

            // add classes
            $(".ui-jqgrid-htable").addClass("table table-bordered table-hover");
            $(".ui-jqgrid-btable").addClass("table table-bordered table-striped");

            $(".ui-pg-div").removeClass().addClass("btn btn-sm btn-primary");
            $(".ui-icon.ui-icon-plus").removeClass().addClass("fa fa-plus");
            $(".ui-icon.ui-icon-pencil").removeClass().addClass("fa fa-pencil");
            $(".ui-icon.ui-icon-trash").removeClass().addClass("fa fa-trash-o");
            $(".ui-icon.ui-icon-search").removeClass().addClass("fa fa-search");
            $(".ui-icon.ui-icon-refresh").removeClass().addClass("fa fa-refresh");
            $(".ui-icon.ui-icon-disk").removeClass().addClass("fa fa-save").parent(".btn-primary").removeClass("btn-primary").addClass("btn-success");
            $(".ui-icon.ui-icon-cancel").removeClass().addClass("fa fa-times").parent(".btn-primary").removeClass("btn-primary").addClass("btn-danger");

            $(".ui-icon.ui-icon-seek-prev").wrap("<div class='btn btn-sm btn-default'></div>");
            $(".ui-icon.ui-icon-seek-prev").removeClass().addClass("fa fa-backward");

            $(".ui-icon.ui-icon-seek-first").wrap("<div class='btn btn-sm btn-default'></div>");
            $(".ui-icon.ui-icon-seek-first").removeClass().addClass("fa fa-fast-backward");

            $(".ui-icon.ui-icon-seek-next").wrap("<div class='btn btn-sm btn-default'></div>");
            $(".ui-icon.ui-icon-seek-next").removeClass().addClass("fa fa-forward");

            $(".ui-icon.ui-icon-seek-end").wrap("<div class='btn btn-sm btn-default'></div>");
            $(".ui-icon.ui-icon-seek-end").removeClass().addClass("fa fa-fast-forward");

        });

        $(window).on('resize.jqGrid', function () {
            $("#jqgrid").jqGrid('setGridWidth', $("#content").width());
        });

       // function formateadorLink(cellvalue, options, rowObject) {
       // 
       //     return "<a href=/Admin/UserManagement/UserMaint/?userid=" + rowObject.AspNetUsersId + ">" + cellvalue + "</a>";
       // }
        function formatTmplteLink(cellvalue, options, rowObject) {

            return "<a href=/Admin/ContractTemplate/Index/?userid=" + rowObject.AspNetUsersId + ">CONTRACT</a>";
        }
    </script>
}

ePark.WebUI/Areas/Admin/Views/UserManagement/UserMaint.cshtml
@model ePark.WebUI.Areas.Admin.Models.UserManagementModel
@{
    ViewBag.Title = "UserMaint";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
        <h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-user"></i> User Management <span>&gt; Manage Users</span></h1>
    </div>
</div>


<section id="widget-grid" class="">

    <div class="well">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search Users...">
            <div class="input-group-btn">
                <button class="btn btn-default btn-primary" type="button">
                    <i class="fa fa-search"></i> Search
                </button>
            </div>
        </div>
    </div>

    <div class="row">

        <article class="col-sm-12 sortable-grid ui-sortable">

            <div class="bActivewidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" role="widget">

                <header role="heading">
                    <div class="bActivewidget-ctrls" role="menu"><a href="@Url.Action("Index", "Dashboard", new {area = "Admin"})" class="button-icon bActivewidget-delete-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Save"><i class="fa fa-save"></i></a>  <a href="@Url.Action("Index", "Dashboard", new {area = "Admin"})" class="button-icon bActivewidget-delete-btn" rel="tooltip" title="" data-placement="bottom" data-original-title="Cancel"><i class="fa fa-times"></i></a></div>
                    <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                    <h2>User Details</h2>

                    <span class="bActivewidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
                </header>

                <div role="content">

                    <div class="widget-body">
                        @using (Html.BeginForm("UserMaint", "UserManagement", FormMethod.Post, new { type = "form", @class = "form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()
                            <fieldset>
                                <legend>User Information</legend>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.Email, "Username", htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        <label class="control-label"><strong>@Html.DisplayTextFor(model => model.User.Email)</strong></label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.FirstName, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.User.FirstName, new { type = "text", @class = "form-control", placeholder = "Enter Email Address...", tabindex = 1, required = "required" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.LastName, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.User.LastName, new { type = "text", @class = "form-control", placeholder = "Enter Email Address...", tabindex = 1, required = "required" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.Address1, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.User.Address1, new { type = "text", @class = "form-control", placeholder = "Enter Email Address...", tabindex = 1, required = "required" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.City, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.User.City, new { type = "text", @class = "form-control", placeholder = "Enter Email Address...", tabindex = 1, required = "required" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.State, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.User.State, new { type = "text", @class = "form-control", placeholder = "Enter Email Address...", tabindex = 1, required = "required" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.PostalCode, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.User.PostalCode, new { type = "text", @class = "form-control", placeholder = "Enter Email Address...", tabindex = 1, required = "required" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.PhonePrimary, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.User.PhonePrimary, new { type = "text", @class = "form-control", placeholder = "Enter Email Address...", tabindex = 1, required = "required" })
                                    </div>
                                </div>
                            </fieldset>
                            <fieldset>
                                <legend>Account Details</legend>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.Email, htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(model => model.User.Email, new { type = "text", @class = "form-control", placeholder = "Enter Email Address...", tabindex = 1, required = "required" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.MccEmployee, htmlAttributes: new {@class = "col-md-2 control-label"})
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            <label>
                                                @Html.CheckBoxFor(model => model.User.MccEmployee.Value, new {type = "checkbox", @class = "checkbox style-0"})<span></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.User.LockoutEnabled, "Account Enabled", htmlAttributes: new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            <label>
                                                @Html.CheckBoxFor(model => model.User.LockoutEnabled, new { type = "checkbox", @class = "checkbox style-0" })<span></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>

                            </fieldset>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12">
                                        <button class="btn btn-primary" name="SubmitEdit" type="submit">
                                            <i class="fa fa-save"></i>
                                            Save
                                        </button>&nbsp;&nbsp;
                                        <button class="btn btn-default" onclick="location.href='@Url.Action("Index", "UserManagement", new {area = "Admin"})'">
                                            Cancel
                                        </button>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </article>
    </div>
</section>